### ISSUE TITLE
Encode of Decode with alignment stuffing returns iobit.ErrOverflow

### ISSUE THREAD

**Issue by marc-ostrow** [Comcast/scte35-go#3]
Here are two such examples of splice info sections that Decode having alignment stuffing, but an Encode of that decoded `SpliceInfoSection` fails with iobit.ErrOverflow.  

- /DA0AABS2+YAAACgFAUALJGCf+/+MSwPcX4AUmXAAAAAAAAMAQpDVUVJRp8xMjEq3pnIPCi6lw==
- /DAvAABS2+YAAACgDwUALJGEf0/+MX7z3AAAAAAADAEKQ1VFSQCfMTIxI6SMuQkzWQI=

`SpliceInfoSection.Decode` is able to parse the sections, each having 3 bytes of alignment stuffing.  When encoding, a buffer is allocated based on `SpliceInfoSection.length` which in turn is based on `SpliceInfoSection.sectionLength` which currently only includes alignment stuffing when the section is encrypted.

The fix is to move line [splice_info_section.go#L371](https://github.com/Comcast/scte35-go/blob/v1.2.1/pkg/scte35/splice_info_section.go#L371) out from (and placed above)  the encryption check.

NOTE:  These are SpliceInserts from the wild, you can't make this stuff up!  ;-)

**Comment by marc-ostrow** [comment]
Testing locally by modifying my local v1.2.1 package, I'm actually getting the correct section length, so the buffer is allocated to be large enough to encode, but now I'm getting "bit underflow" errors. ;-(

Looking closer... (sorry).

**Comment by blahspam** [comment]
Fixed in v1.2.2
