### ISSUE TITLE
SpliceInfoSection.SAPType defaults to SAPType1

### ISSUE THREAD

**Issue by tjjwilson** [Comcast/scte35-go#30]
The SCTE 35 2022b spec lists the SAPType field as:

@sapType [Optional; xsd:unsignedShort; default=3]

However, if you encode a SCTE 35 XML document that does not specify an sapType attribute for the SpliceInfoSection, then decode the resulting binary, the sapType specified in the decoded XML shows an sapType of '0', specifying Type 1 stream access point (Closed GOP with no leading pictures).

**Comment by blahspam** [comment]
@tjjwilson Nice catch. I'll work on getting a fix and patch release out this week.
